config/routes.rb
Rails.application.routes.draw do
  get 'order/new'

  resources :donut

  devise_for :users
  root 'home#index'

end

app/models/donut.rb
class Donut < ActiveRecord::Base
    
  has_many :list_items
  has_many :orders, :through => :list_items
end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :donut
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  
  has_many :list_items
  has_many :donuts, :through => :list_items
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/donut_controller.rb
class DonutController < ApplicationController
  def index
    @donuts = Donut.all
  end
  def new
    @donut = Donut.new
  end
  
  def create
    @donut = Donut.new(donut_params)
    
    if @donut.save
      redirect_to donut_index_path
    else
      render 'new'
    end
  end
  
  
  private
  
  def donut_params
    params.require(:donut).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  
  def new
    @order = Order.new
    @new_order = @order.donuts << Donut.all

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donut_helper.rb
module DonutHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/donut/index.html.erb
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <% @donuts.each do |donut| %>
            <tr>
                <th><%= donut.name %></th>
                <th><%= link_to "Delete", donut_path(donut), method: :delete, class: "btn btn-xs btn-danger" %></th>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/donut/new.html.erb
<%= form_for @donut, url: {action: 'create'} do |f| %>
  <%=  f.label :name%>
  <%=  f.text_field :name%>
  
  <%=  f.submit%>
  
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-xs btn-danger"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/order/new.html.erb
<h1>Order#new</h1>
<p>Find me in app/views/order/new.html.erb</p>